#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DeliveryPersonApp.Android.Resource", IsApplication=true)]

namespace DeliveryPersonApp.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int ambientEnabled = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonSize = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cameraBearing = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cameraMaxZoomPreference = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cameraMinZoomPreference = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int circleCrop = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int colorScheme = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int imageAspectRatio = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int imageAspectRatioAdjust = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int latLngBoundsNorthEastLatitude = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int latLngBoundsNorthEastLongitude = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int latLngBoundsSouthWestLatitude = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int latLngBoundsSouthWestLongitude = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int liteMode = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int mapType = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int scopeUris = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int uiCompass = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int uiMapToolbar = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int uiRotateGestures = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int uiScrollGestures = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int uiScrollGesturesDuringRotateOrZoom = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int uiTiltGestures = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int uiZoomControls = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int uiZoomGestures = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int useViewLifecycle = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int zOrderOnTop = 2130771997;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int common_google_signin_btn_text_dark = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int common_google_signin_btn_text_dark_default = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int common_google_signin_btn_text_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int common_google_signin_btn_text_dark_focused = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int common_google_signin_btn_text_dark_pressed = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int common_google_signin_btn_text_light = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int common_google_signin_btn_text_light_default = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int common_google_signin_btn_text_light_disabled = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int common_google_signin_btn_text_light_focused = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int common_google_signin_btn_text_light_pressed = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int common_google_signin_btn_tint = 2130837514;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int common_full_open_on_phone = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int common_google_signin_btn_icon_dark = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int common_google_signin_btn_icon_dark_focused = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int common_google_signin_btn_icon_dark_normal = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int common_google_signin_btn_icon_disabled = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int common_google_signin_btn_icon_light = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int common_google_signin_btn_icon_light_focused = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int common_google_signin_btn_icon_light_normal = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int common_google_signin_btn_icon_light_normal_background = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int common_google_signin_btn_text_dark = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int common_google_signin_btn_text_dark_focused = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int common_google_signin_btn_text_dark_normal = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int common_google_signin_btn_text_dark_normal_background = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int common_google_signin_btn_text_disabled = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int common_google_signin_btn_text_light = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int common_google_signin_btn_text_light_focused = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int common_google_signin_btn_text_light_normal = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int common_google_signin_btn_text_light_normal_background = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int googleg_disabled_color_18 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int googleg_standard_color_18 = 2130903060;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int adjust_height = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int adjust_width = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int auto = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int contentFrame = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int dark = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int deliverMapFragment = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int emailEditText = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int hybrid = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int icon_only = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int light = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int mainTabLayout = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int none = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int normal = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int passwordEditText = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int pickupMapFragment = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int registerButton = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int registerConfirmEditText = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int registerEmailEditText = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int registerPasswordEditText = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int registerSaveButton = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int satellite = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int signinButton = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int standard = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int terrain = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int wide = 2130968600;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int Deliver = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int Main = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int PickUp = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int Register = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int Tabs = 2131099652;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int common_google_play_services_enable_button = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int common_google_play_services_enable_text = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int common_google_play_services_enable_title = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int common_google_play_services_install_button = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int common_google_play_services_install_text = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int common_google_play_services_install_title = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int common_google_play_services_notification_channel_name = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int common_google_play_services_notification_ticker = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int common_google_play_services_unknown_issue = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int common_google_play_services_unsupported_text = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int common_google_play_services_update_button = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int common_google_play_services_update_text = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int common_google_play_services_update_title = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int common_google_play_services_updating_text = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int common_google_play_services_wear_update_text = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int common_open_on_phone = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int common_signin_button_text = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int common_signin_button_text_long = 2131165202;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010009,0x7F01000B,0x7F01000C }
			public static int[] LoadingImageView = new int[] {
					2130771977,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010000,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D }
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 0
			public const int MapAttrs_ambientEnabled = 0;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraMaxZoomPreference = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraMinZoomPreference = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTargetLat = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraTargetLng = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_cameraTilt = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_cameraZoom = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_liteMode = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_mapType = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_uiCompass = 14;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 16
			public const int MapAttrs_uiRotateGestures = 16;
			
			// aapt resource value: 17
			public const int MapAttrs_uiScrollGestures = 17;
			
			// aapt resource value: 18
			public const int MapAttrs_uiScrollGesturesDuringRotateOrZoom = 18;
			
			// aapt resource value: 19
			public const int MapAttrs_uiTiltGestures = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_uiZoomControls = 20;
			
			// aapt resource value: 21
			public const int MapAttrs_uiZoomGestures = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_useViewLifecycle = 22;
			
			// aapt resource value: 23
			public const int MapAttrs_zOrderOnTop = 23;
			
			// aapt resource value: { 0x7F010001,0x7F01000A,0x7F010013 }
			public static int[] SignInButton = new int[] {
					2130771969,
					2130771978,
					2130771987};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
